server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Kolkata
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update    # for dev only; use migrations in prod
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

# Example Feign base URL (could point to another service or this one)
feign:
  userService:
    base-url: http://localhost:8080

security:
  jwt:
    secret: "replace-with-256-bit-secret-min-32-chars-1234567890abcdef!"  # HS256 secret
    expiry-minutes: 60