server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Kolkata
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update    # for dev only; use migrations in prod
    show-sql: true
    properties:
      hibernate.format_sql: true

# Example Feign base URL (could point to another service or this one)
feign:
  userService:
    base-url: http://localhost:8080
